//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovoiWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termostat
    {
        public int ID_T { get; set; }
        public Nullable<int> MinTemp { get; set; }
        public Nullable<int> MaxTemp { get; set; }
        public int ID_P { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
